//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToditoRentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizarPagos
    {
        public int IdAutorizar { get; set; }
        public string De { get; set; }
        public string Para { get; set; }
        public Nullable<double> TotalPago { get; set; }
        public string StatusPago { get; set; }
        public Nullable<System.DateTime> FechaGenerado { get; set; }
    }
}
