//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToditoRentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.Cancelacion = new HashSet<Cancelacion>();
        }
    
        public int IdContrato { get; set; }
        public string Arrendatario { get; set; }
        public string Arrendador { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<bool> Status { get; set; }
        public int IdRenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancelacion> Cancelacion { get; set; }
        public virtual Renta Renta { get; set; }
    }
}
