//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToditoRentas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToditoRentasEntities : DbContext
    {
        public ToditoRentasEntities()
            : base("name=ToditoRentasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<AutorizarPagos> AutorizarPagos { get; set; }
        public virtual DbSet<CalificacionProductos> CalificacionProductos { get; set; }
        public virtual DbSet<CalificacionUsuarios> CalificacionUsuarios { get; set; }
        public virtual DbSet<Cancelacion> Cancelacion { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<ComentarioProductos> ComentarioProductos { get; set; }
        public virtual DbSet<ComentarioUsuarios> ComentarioUsuarios { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<CuentaBancaria> CuentaBancaria { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Filtro> Filtro { get; set; }
        public virtual DbSet<FoliosAplica> FoliosAplica { get; set; }
        public virtual DbSet<FotoProducto> FotoProducto { get; set; }
        public virtual DbSet<FotoUsuarios> FotoUsuarios { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<ParametrosSis> ParametrosSis { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Publicacion> Publicacion { get; set; }
        public virtual DbSet<PublicacionRenta> PublicacionRenta { get; set; }
        public virtual DbSet<Renta> Renta { get; set; }
        public virtual DbSet<RespuestaMensaje> RespuestaMensaje { get; set; }
        public virtual DbSet<Sancion> Sancion { get; set; }
        public virtual DbSet<Sugerencia> Sugerencia { get; set; }
        public virtual DbSet<SugerenciaUsuario> SugerenciaUsuario { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
