//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToditoRentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaMensaje
    {
        public int IdRespuesta { get; set; }
        public string Descripcion { get; set; }
        public int IdMensaje { get; set; }
        public int IdAdministrador { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Mensaje Mensaje { get; set; }
    }
}
